version: "3.9"
services:
  ggb:
    container_name: ggb
    build:
      context: ./ggb
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - gg
  ggf:
    container_name: ggf
    build:
      context: ./ggf
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - gg

networks:
  gg:
