version: "3.9"
services:
    ggb:
        container_name: gg_backend
        build:
            context: ./ggb
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        networks:
            - gg
    ggf:
        container_name: gg_frontend
        build:
            context: ./ggf
            dockerfile: Dockerfile
        ports:
            - "5173:3000"
        networks:
            - gg

networks:
    gg:
