version: "3.9"
services:
    backend:
        container_name: gg-backend
        build:
            context: ./global-getaways-backend
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - .:/backend
            - logvolume01:/var/backend/log
    frontend:
        container_name: gg-frontend
        build:
            context: ./global-getaways-frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - .:/frontend
            - logvolume02:/var/frontend/log
volumes:
    logvolume01: {}
    logvolume02: {}
